### PR TITLE
Improve LambdaFunction naming and prefix convention

### PR DESCRIPTION
**Pull request by maurocasas**
Due to using a `.` in your `APP_NAME` value we were encountering issues when deploying our new versions.

In order to work around this, I'm proposing to change how the `prefix` is built, as well as the `name` for the function using the previously mentioned `prefix`.

I have also removed the usage of `str_replace` and use `Str::slug` instead because `str_replace` scope is too narrow only replacing spaces and allowing special characters (such as dots, commas and so)

`sidecar.php` config has been extended to allow customization of the Lambda naming prefix, defaulting at `SC`

### CODE REVIEW

**Comment by aarondfrancis** [comment]
@maurocasas I haven't forgotten about this, sorry for the delay.

At this point, I'm trying to figure out if adding the str::slug is a breaking change or not. I think it might be, so I may try to just replace the `.` manually instead. What do you think about that?

**Comment by danatemple** [comment]
Minor suggestion: How about an option to leave out the -Sidecar- bit of the name, given that you can give it a 'sc' prefix or use the default 'SC'?

I've ended up with names like:

   sc-dev-devname-Sidecar-MyFunction   (developer, individual)
   sc-regress-branchname-Sidecar-MyFunction   (CI pipeline, individual per branch)

i.e. I'm using 'sc' already to put them in a Sidecar namespace, having Sidecar repeated in the name is kind of redundant.

**Comment by aarondfrancis** [comment]
@danatemple yeah I agree, it gets to be a bit unwieldy and verbose.

For that example, where is the `Sidecar` coming from? Are your functions in `App\Sidecar\**`? If so, you can control that part via the `name()` method on your function. By default it tries to use the class name (including the namespace) but that's up to you.

I replace `App` by default, and in the next major version I could maybe replace `App\Sidecar` by default too.

**Comment by danatemple** [comment]
@aarondfrancis aha, it must be from the namespace. Didn't realize that, or that name() would remove this part.

But yes, good idea to remove, as it will always be a redundant section in the middle of the name, assuming there is a prefix that identifies the function as Sidecar.

**Comment by aarondfrancis** [comment]
> But yes, good idea to remove, as it will always be a redundant section in the middle of the name, assuming there is a prefix that identifies the function as Sidecar.

Yup, agreed. Thanks for the idea!

**Comment by vriendvandeshow** [comment]
This seems like a solid improvement for the prefix() functionality clearing a couply of open issues / other PRs, so would definitely vouch for this.

**Comment by aarondfrancis** [comment]
Thanks for opening this, I added a few tests and changed the implementation just a bit. I'm not quite ready to tag a new release, as I want to clean up the other naming issues first, but I'll tag something soon. Thanks again @maurocasas.

**Pull request merged**
