### PR TITLE
Update Zipstream dependency

### PR DESCRIPTION
**Pull request by bookwyrm**
Zipstream v2 requires `psr/http-message` v1. I wanted to use sidecar in my project but I already had `psr/http-message` v2 in place. Updating Zipstream to v3 allows `psr/http-message` v2 but requires other changes related to argument format.

### CODE REVIEW

**Comment by orkhanahmadov** [comment]
@aarondfrancis whenever possible can you please merge this? It blocks upgrading/using other packages where `maennchen/zipstream-php` v3 is required, like [spatie/laravel-medialibrary](https://github.com/spatie/laravel-medialibrary/blob/main/composer.json#L35) v11.

**Comment by orkhanahmadov** [comment]
@aarondfrancis can you please take a look into this one too? Even https://github.com/hammerstonedev/sidecar/pull/141 is merged, zip dependency is still blocking us from upgrading to Laravel 11 when using [spatie/laravel-medialibrary](https://github.com/spatie/laravel-medialibrary).

**Comment by lionslair** [comment]
bump

**Comment by aarondfrancis** [comment]
Merged in another PR! Thanks all

**Pull request closed without merging**
