### PR TITLE
Add ability to configure ephemeral storage size

### LINKED ISSUE #70: Add ability to configure ephemeral storage
Would be nice to be able to do this right from Sidecar, just like memory and timeout. I'll work on a PR 😊

### PR DESCRIPTION
**Pull request by bakerkretzmar**
Adds a `storage` method and config option to allow configuring a Lambda's ephemeral storage.

Tested in my own AWS account and ~AWS appears to completely ignore the parameter.... will keep fiddling with it~ works like a charm.

Closes #70.

### CODE REVIEW

**Comment by aarondfrancis** [comment]
Hmm I wonder why it's just being ignored, I don't see anything obvious here that's missing! I'll dig into the API docs a bit more to see if I can find anything subtle.

**Comment by bakerkretzmar** [comment]
Yeah this is really frustrating 😅 I tried configuring Sidecar again from scratch, tried a different region, tried all kinds of weird combinations of `EphemeralStorage` and `Size` as parameters, can't seem to get it to even recognize that I'm sending it in.

**Comment by bakerkretzmar** [comment]
Works with the `aws` CLI too.

**Comment by bakerkretzmar** [comment]
Ouf my bad @aarondfrancis the app I'm in was using a weird wrapper around the AWS PHP package and the underlying version was 4 months old. Updated and this works perfectly!

**Pull request merged**
